### ISSUE TITLE
entity 말고 DTO를 사용하는 이유가 궁금합니다!

### ISSUE THREAD

**Issue by Hun425** [seonminKim1122/Spring_Prac#1]
저는 entity로 해서요,,,,,

**Comment by seonminKim1122** [comment]
엔티티는 연관관계를 맺기 위해 여러 엔티티간 참조가 발생하기 때문에 이걸 리턴하면 JSON 으로 변환할 때 서로 순환 참조가 발생하게 됩니다.

따라서 일반적으로 엔티티는 DB 에 저장하고 꺼내오는 용도로만 사용하고 계층 간 데이터 전달 시에는 Data Transfer Object(DTO) 라는 걸 사용합니다.
