### ISSUE TITLE
FetchType의 차이가 정확이 뭔지 궁금합니다!

### ISSUE THREAD

**Issue by Hun425** [seonminKim1122/Spring_Prac#2]
Eager와 Lazy가 있던데 정확히 무슨 차이인지 알아봐도 잘 모르겠어요

**Comment by seonminKim1122** [comment]
Eager는 메인 엔티티를 부르면 연관관계가 맺어진 것까지 한 번에 같이 조회해오는 방식이고, Lazy 는 실제로 연관관계를 맺은 엔티티를 호출하는 시점에 DB에서 조회해오는 방식입니다.

Eager 는 게시글-댓글 관계라고 할 때 게시글을 조회할 때 바로 댓글을 다 불러오는 방식입니다.

하지만 댓글이 필요없는 상황이 있을 수 있기 때문에(ex : 게시글 목록 조회) 특수한 경우가 아니라면 Lazy 로 설정해서 실제로 연관관계 맺은 게 호출되는 시점에 쿼리를 날리게 하는 게 좋다고 하네요.
