### ISSUE TITLE
@RequestAttribute에 대해서 궁금합니다!

### ISSUE THREAD

**Issue by Hun425** [seonminKim1122/Spring_Prac#3]
유저 로그인이 되어있으면 자동으로 요청 속성에 user 정보를 보내니까 
그 정보를 사용한다는 건가요?

**Comment by seonminKim1122** [comment]
그건 common 패키지의 Interceptor 코드를 보시면 됩니다!!

일단 해당 아노테이션은 HttpServletRequest 객체에 저장된 Attribute 를 가져오기 위한 겁니다.

저는 세션 방식의 인증 시스템을 구현하면서 로그인을 필요로 하는 요청이 오면 Interceptor에서 세션이 유효한지 확인하고, 
유효하다면 UserRepository 를 이용해 User 객체를 조회해 HttpServletRequest 에 setAttribute 를 해서 넘겨주고 있습니다.

이걸 꺼내서 쓰기위해 저 어노테이션을 붙였습니당

**Comment by seonminKim1122** [comment]
참고로 Interceptor는 DispatcherServlet과 Controller 사이에 위치해서 요청이 들어오면 이와 관련된 사전 작업을 처리하거나, 응답을 보내기 전 필요한 작업을 처리하는 등의 목적으로 사용할 수 있습니다
