### ISSUE TITLE
게시글에 유저를 연결하는 방식이 궁금합니다

### ISSUE THREAD

**Issue by Hun425** [seonminKim1122/Spring_Prac#4]
현재 엔티티에서 user 객체 자체를 
    @ManyToOne
    private User user;
    형식으로 연결하는데, 이렇게 되면 DB에 객체자체를 저장하게 되나요?
    아니면 어떤 형식으로 저장이 되어서 @RequestAttribute를 사용해서 가져오게 되는지 궁금합니다..

**Comment by seonminKim1122** [comment]
@RequestAttribute는 엔티티끼리의 연관관계나 DB와는 무관합니다. HttpRequestServlet 객체에 setAttribute 메서드를 사용하면 key-value 형태로 값을 저장할 수 있는데 해당 어노테이션은 단순히 저장한 key로 value를 꺼내오는 역할입니다.

@ManyToOne 은 연관관계를 맺을 때 사용하는데 Board-User 관계에서는 여러 개의 게시글이 한 명의 유저와 관계를 맺을 수 있으므로 사용하는 것이고 이렇게 관계를 맺으면 DB 에 저장될 때는 Board 테이블이 User 테이블의 pk를 외래키로 가지게 됩니다.
